homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

##
## BORNE
##

borne_index:
    path:     /borne
    defaults: { _controller: AppBundle:Borne:index }
    methods:    [GET]

borne_new:
    path:     /borne/new
    defaults: { _controller: AppBundle:Borne:new }
    methods:    [GET, POST]

borne_show:
    path:     /borne/{id}
    defaults: { _controller: AppBundle:Borne:show }
    methods:    [GET, POST]

borne_edit:
    path:     /borne/{id}/edit
    defaults: { _controller: AppBundle:Borne:edit }
    methods:    [GET, POST]

borne_delete:
    path:     /borne/{id}
    defaults: { _controller: AppBundle:Borne:delete }
    methods:    [DELETE]

##
## ANNUAIRE
##

annuaire_index:
    path:     /annuaire
    defaults: { _controller: AppBundle:Annuaire:index }
    methods:    [GET]

annuaire_new:
    path:     /annuaire/new
    defaults: { _controller: AppBundle:Annuaire:new }
    methods:    [GET, POST]

annuaire_show:
    path:     /annuaire/{id}
    defaults: { _controller: AppBundle:Annuaire:show }
    methods:    [GET, POST]

annuaire_edit:
    path:     /annuaire/{id}/edit
    defaults: { _controller: AppBundle:Annuaire:edit }
    methods:    [GET, POST]

annuaire_delete:
    path:     /annuaire/{id}
    defaults: { _controller: AppBundle:Annuaire:delete }
    methods:    [DELETE]

## CATÉGORIES

categorie_annuaire_index:
    path:     /categorie_annuaire
    defaults: { _controller: AppBundle:CategoriesAnnuaire:index }
    methods:    [GET]

categorie_annuaire_new:
    path:     /categorie_annuaire/new
    defaults: { _controller: AppBundle:CategoriesAnnuaire:new }
    methods:    [GET, POST]

categorie_annuaire_edit:
    path:     /categorie_annuaire/{id}/edit
    defaults: { _controller: AppBundle:CategoriesAnnuaire:edit }
    methods:    [GET, POST]

categorie_annuaire_delete:
    path:     /categorie_annuaire/{id}
    defaults: { _controller: AppBundle:CategoriesAnnuaire:delete }
    methods:    [DELETE]

upload_img:
    path:     /upload_img/
    defaults: { _controller: AppBundle:Image:uploadImage }
    methods:    [GET, POST]

##
## INFOS UTILES
##

infosutiles_index:
    path:     /infosutiles
    defaults: { _controller: AppBundle:InfosUtiles:index }
    methods:    [GET]

infosutiles_new:
    path:     /infosutiles/new
    defaults: { _controller: AppBundle:InfosUtiles:new }
    methods:    [GET, POST]

infosutiles_show:
    path:     /infosutiles/{id}
    defaults: { _controller: AppBundle:InfosUtiles:show }
    methods:    [GET, POST]

infosutiles_edit:
    path:     /infosutiles/{id}/edit
    defaults: { _controller: AppBundle:InfosUtiles:edit }
    methods:    [GET, POST]

infosutiles_delete:
    path:     /infosutiles/{id}
    defaults: { _controller: AppBundle:InfosUtiles:delete }
    methods:    [DELETE]


type_infos_index:
    path:     /type_infos
    defaults: { _controller: AppBundle:CategoriesAnnonce:index }
    methods:    [GET]

type_infos_new:
    path:     /type_infos/new
    defaults: { _controller: AppBundle:CategoriesAnnonce:new }
    methods:    [GET, POST]

type_infos_show:
    path:     /type_infos/{id}
    defaults: { _controller: AppBundle:CategoriesAnnonce:show }
    methods:    [GET, POST]

type_infos_edit:
    path:     /type_infos/{id}/edit
    defaults: { _controller: AppBundle:CategoriesAnnonce:edit }
    methods:    [GET, POST]

type_infos_delete:
    path:     /type_infos/{id}
    defaults: { _controller: AppBundle:CategoriesAnnonce:delete }
    methods:    [DELETE]

##
## PETITES ANNONCES
##
petitesannonces_index:
    path:     /petitesannonces
    defaults: { _controller: AppBundle:PetitesAnnonces:index }
    methods:    [GET]

petitesannonces_new:
    path:     /petitesannonces/new
    defaults: { _controller: AppBundle:PetitesAnnonces:new }
    methods:    [GET, POST]

petitesannonces_show:
    path:     /petitesannonces/{id}
    defaults: { _controller: AppBundle:PetitesAnnonces:show }
    methods:    [GET, POST]

petitesannonces_edit:
    path:     /petitesannonces/{id}/edit
    defaults: { _controller: AppBundle:PetitesAnnonces:edit }
    methods:    [GET, POST]

petitesannonces_delete:
    path:     /petitesannonces/{id}
    defaults: { _controller: AppBundle:PetitesAnnonces:delete }
    methods:    [DELETE]



categorie_annonce_index:
    path:     /categorie_annonce
    defaults: { _controller: AppBundle:CategoriesAnnonce:index }
    methods:    [GET]

categorie_annonce_new:
    path:     /categorie_annonce/new
    defaults: { _controller: AppBundle:CategoriesAnnonce:new }
    methods:    [GET, POST]

categorie_annonce_show:
    path:     /categorie_annonce/{id}
    defaults: { _controller: AppBundle:CategoriesAnnonce:show }
    methods:    [GET, POST]

categorie_annonce_edit:
    path:     /categorie_annonce/{id}/edit
    defaults: { _controller: AppBundle:CategoriesAnnonce:edit }
    methods:    [GET, POST]

categorie_annonce_delete:
    path:     /categorie_annonce/{id}
    defaults: { _controller: AppBundle:CategoriesAnnonce:delete }
    methods:    [DELETE]